### PR TITLE
Create Docker image & Docker-Compose

### PR DESCRIPTION
**Pull request by ajpl**
You can read more about this PR over at #255

### CODE REVIEW

**Comment by ajpl** [comment]
This is still a WIP there are some improvements to be done. But it is working at the moment...

**Comment by ajpl** [comment]
@kikeelectronico this is ready for review, follow the steps on the README to test it. Since the build & push for the images won't be triggered up until this is merged & a release is made, please swap `ghcr.io/kikeelectronico` in the `docker-compose.yml` file to `ghcr.io/ajpl` since I've already triggered the build & push process on my account.

**Comment by ajpl** [comment]
I force pushed to squash all the commits.

**Comment by kikeelectronico** [comment]
Awesome work!

I am getting a 502 error when trying to config the user name and password after `docker-compose up -d`.

I have changed to `ghcr.io/ajpl `and I have created my own .env file.

Any idea why?

```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.19.3</center>
</body>
</html>
```

The output of docker compose:

```
Creating network "homeware-lan_default" with the default driver
Creating volume "homeware-lan_html" with default driver
Creating volume "homeware-lan_certs" with default driver
Creating volume "homeware-lan_vhostd" with default driver
Creating volume "homeware-lan_mosquitto-data" with default driver
Creating volume "homeware-lan_redis-data" with default driver
Pulling redis (redis:6.0)...
6.0: Pulling from library/redis
45b42c59be33: Pull complete
5ce2e937bf62: Pull complete
2a031498ff58: Pull complete
f598dcc3e193: Pull complete
482863b1501c: Pull complete
9c92d1e14478: Pull complete
Digest: sha256:e8e719d8b2c8b6c807a6aa6c0b21dfe57e7ef4bd4f9d919c9464c3ce26c90534
Status: Downloaded newer image for redis:6.0
Pulling mosquitto (eclipse-mosquitto:2.0)...
2.0: Pulling from library/eclipse-mosquitto
f84cab65f19f: Pull complete
a0f4cca88c89: Pull complete
a8085b530541: Pull complete
Digest: sha256:f0c6aa19d4b9a2f6e0f935633b867f26c909f12fff32ae4559695d35dbaa806b
Status: Downloaded newer image for eclipse-mosquitto:2.0
Pulling homeware-lan-back-mqtt (ghcr.io/ajpl/homewarelan-back:)...
latest: Pulling from ajpl/homewarelan-back
45b42c59be33: Already exists
8cd3485318db: Pull complete
2f564129f025: Pull complete
cf1573f5a21e: Pull complete
a887b24f576c: Pull complete
caa4378804a8: Pull complete
c3dd66604b04: Pull complete
d68d8b062ea2: Pull complete
361cbd830cf9: Pull complete
38e4cfbff3b6: Pull complete
a960d24e811a: Pull complete
9aa698c45f6d: Pull complete
Digest: sha256:ade72251a006c4f50536c99a30415d5846b89e1b278d1a87c1f857ea6a48320b
Status: Downloaded newer image for ghcr.io/ajpl/homewarelan-back:latest
Pulling nginx-proxy (jwilder/nginx-proxy:)...
latest: Pulling from jwilder/nginx-proxy
bb79b6b2107f: Pull complete
111447d5894d: Pull complete
a95689b8e6cb: Pull complete
1a0022e444c2: Pull complete
32b7488a3833: Pull complete
c45cf71bc68c: Pull complete
00d28348da58: Pull complete
190f1720abb7: Pull complete
a99149d671c6: Pull complete
c7e9f170fd7c: Pull complete
accc49186289: Pull complete
e67d699eb6f8: Pull complete
Digest: sha256:695db064e3c07ed052ea887b853ffba07e8f0fbe96dc01aa350a0d202746926b
Status: Downloaded newer image for jwilder/nginx-proxy:latest
Pulling nginx (ghcr.io/ajpl/homewarelan-nginx:)...
latest: Pulling from ajpl/homewarelan-nginx
45b42c59be33: Already exists
8acc495f1d91: Pull complete
ec3bd7de90d7: Pull complete
19e2441aeeab: Pull complete
f5a38c5f8d4e: Pull complete
83500d851118: Pull complete
73b8a1059f3d: Pull complete
56c6ffe8c397: Pull complete
41b54259ca06: Pull complete
Digest: sha256:21b3a50cff5d2fc7377d222c73d9818a2282d6ab474defe11f1dc21f623b54c0
Status: Downloaded newer image for ghcr.io/ajpl/homewarelan-nginx:latest
Pulling letsencrypt (jrcs/letsencrypt-nginx-proxy-companion:)...
latest: Pulling from jrcs/letsencrypt-nginx-proxy-companion
4c0d98bf9879: Pull complete
cbd2d253a464: Pull complete
3acee8463d38: Pull complete
45804c8ab96c: Pull complete
a21d1a6ef64b: Pull complete
2a98d70840e1: Pull complete
Digest: sha256:639e504afd660ec0a16154d3df04f9f395554f8134bab7caf0efab499a60b342
Status: Downloaded newer image for jrcs/letsencrypt-nginx-proxy-companion:latest
Creating homeware-lan_mosquitto_1   ... done
Creating homeware-lan_redis_1       ... done
Creating homeware-lan_nginx-proxy_1 ... done
Creating homeware-lan_letsencrypt_1 ... done
Creating homeware-lan_homeware-lan-back-mqtt_1  ... done
Creating homeware-lan_homeware-lan-back-tasks_1 ... done
Creating homeware-lan_homeware-lan-back-api_1   ... done
Creating homeware-lan_nginx_1                   ... done
```

**Comment by ajpl** [comment]
Can you please run `docker-compose up` without the `-d` and post the output ? That way the stdout of the containers does not go to the background. I suspect there is one container that is failing, probably the `homewarelan-nginx`  one is alright if you can reach the UI. But the `homewarelan-back` could be failing if you are doing an API call as you said.

Thanks!!

**Comment by kikeelectronico** [comment]
Finally. Could you please PR to dev? There are some things at the web interface that must be changed to avoid confuse the user. I will release it all together in the next release.

**Comment by ajpl** [comment]
Glad that it finally worked! I changed the branch from `master` to `dev` as requested.

**Comment by kikeelectronico** [comment]
Thank you :-)

**Pull request merged**
